name: 'mdBook to JSON file'
description: 'A GitHub Action that takes an mdBook url input and generates an indexed JSON file of all pages.'
inputs:
  github_token:
    description: 'Github token to be able to create and push the output branch'
    required: true
  mbBook_url:
    description: 'Enter url to mdBook based wiki'
    required: true
    default: "https://rust-lang.github.io/mdBook/"
  reprocess_cache:
    description: 'If all queries should be regenerated or not'
    required: false
    default: false
  output_branch:
    description: 'branch where the json will be pushed to'
    required: false
    default: "GET"
branding:
  icon: 'file-text'
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Chrome
      uses: logikal-io/install-chrome@v1.0.1
      with:
        version: 113.0.5672.63-1
    - name: Check out repo
      uses: actions/checkout@v3
      with:
        repository: 'EzioTheDeadPoet/actions-mdBook-indexer'
        fetch-depth: 0
    - name: Install Python Dependencies
      run: pip install -r ./requirements.txt
      shell: bash
    - name: Index mdBook to JSON
      id: index_task
      run: python src/generate_index_JSON.py ${{ inputs.mbBook_url }} ${{ inputs.queries_json_raw }} ${{inputs.reprocess_cache}}
      shell: bash
    - name: Deploy Data
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ./src/out
        publish_branch: ${{ inputs.output_branch }}
