name: 'mdBook raw.JSON static API Generator'
description: 'A GitHub Action that takes an mdBook url input and generates an indexed JSON file of all pages.'
inputs:
  github_token:
    description: 'Github token required to push the json files to the "api" branch. \n Using "secrets.GITHUB_TOKEN" is recommened.'
    required: true
  mbBook_url:
    description: 'mdBook based website, that you want to search via an "api"'
    required: true
  api_repo:
    description: 'repository housing the "api"'
    required: true
  get_branch:
    description: 'Branch name for the branch that will be housing the json files for the "api" to GET. Default = `"GET"`'
    required: true
    default: "GET"
  post_branch:
    description: 'Branch name for the branch to configure the list of queries. Default = `"POST"`'
    required: true
    default: "POST"
  regenerate_cache:
    description: 'Regenerates the whole queries cache when `true`. Should only be used when the mdBook site updated. Default = `false`'
    required: false
    default: "False"
branding:
  icon: search
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Chrome
      uses: logikal-io/install-chrome@v1.0.1
      with:
        version: 113.0.5672.63-1
    - name: Install API Generator (Checkout Code)
      uses: actions/checkout@v3
      with:
        repository: 'EzioTheDeadPoet/mdBook_rawJSON_api_generator'
    - name: Get API Cache [${{ inputs.get_branch }}] Branch
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.api_branch }}
        path: ./src/out
        fetch-depth: 0
    - name: Get API input [${{ inputs.post_branch }}] Branch
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.api_branch }}
        path: ./src/input
        fetch-depth: 0
    - name: Install Python Dependencies
      run: pip install -r ./requirements.txt
      shell: bash
    - name: Generate raw.JSON mdBook api
      id: index_task
      run: python src/generate_index_JSON.py ${{ inputs.mbBook_url }} ${{inputs.regenerate_cache}}
      shell: bash
    - name: Deploy raw.JSON mdBook api
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ./src/out
        publish_branch: ${{ inputs.get_branch }}
