name: Regenerate Cache
on:
  workflow_run:
    workflows: ["pages-build-deployment"] # Obviously only works if you use this in the same repository as your mdBook
    types:
      - completed
  workflow_dispatch:

jobs:
    get-num-square:
      runs-on: ubuntu-latest
      name: Testing functionality
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Run PSEUDO-API Generator
          id: mdBook_site_to_JSON
          uses: ./
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            mbBook_url: https://rust-lang.github.io/mdBook/
            api_repo: ${{ github.repository }}
            api_branch: API
            regenerate_cache: true
